{{ if .Values.nfc_monitoring.additions.dashboard_sidecar.enabled -}}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/component: graphing
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: grafana
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
    app.kubernetes.io/version: {{ $.Chart.Version }}
  name: Grafana-Sidecar
roleRef:
  kind: ClusterRole
  name: Grafana-Sidecar
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: grafana
    namespace: "{{ .Values.nfc_monitoring.grafana.namespace }}"
{{- end }}
