{{ if .Values.nfc_monitoring.kube_monitor_proxy.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-monitor-proxy
  labels:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: kube-monitor-proxy
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
    app.kubernetes.io/version: {{ $.Chart.Version }}
rules:
- apiGroups: ["authentication.k8s.io"]
  resources:
  - tokenreviews
  verbs: ["create"]
- apiGroups: ["authorization.k8s.io"]
  resources:
  - subjectaccessreviews
  verbs: ["create"]

{{ end }}