---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-monitor-proxy
  labels:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/name: kube-monitor-proxy
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
    app.kubernetes.io/version: {{ $.Chart.Version }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-monitor-proxy
subjects:
- kind: ServiceAccount
  name: kube-monitor-proxy
  namespace: monitoring
