---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasourceList
items:
  {{ range .Values.nfc_monitoring.grafana.DataSources }}
  - apiVersion: grafana.integreatly.org/v1beta1
    kind: GrafanaDatasource
    metadata:
      name: {{ .name }}
      namespace: "{{ $.Values.nfc_monitoring.grafana.namespace }}"
      labels:
        app.kubernetes.io/component: dashboard
        app.kubernetes.io/instance: k8s
        app.kubernetes.io/name: grafana
        app.kubernetes.io/managed-by: {{ $.Release.Service }}
        app.kubernetes.io/part-of: {{ $.Chart.Name }}
        app.kubernetes.io/version: {{ $.Chart.Version }}
    spec:
      instanceSelector:
        matchLabels:
          app.kubernetes.io/component: graphing
          app.kubernetes.io/instance: k8s
          app.kubernetes.io/name: grafana
      allowCrossNamespaceImport: true
      datasource:
        {{ toYaml . | nindent 8 }}

  {{ end }}
