{{ if .Values.nfc_monitoring.alert_manager.ingress.enabled | default "false" | bool -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alert_manager
  namespace: "{{ .Values.nfc_monitoring.alert_manager.namespace }}"
  annotations:
    {{ toYaml $.Values.nfc_monitoring.alert_manager.ingress.annotations | nindent 4 }}
spec:
  {{ toYaml $.Values.nfc_monitoring.alert_manager.ingress.spec | nindent 2 }}

{{ end }}

