---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    {{ toYaml $.Values.nfc_monitoring.alert_manager.labels | nindent 4 }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/version: {{ $.Chart.Version }}
  name: alertmanager-main
  namespace: {{ .Values.nfc_monitoring.alert_manager.namespace | quote }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{ toYaml $.Values.nfc_monitoring.alert_manager.labels | nindent 6 }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/part-of: {{ $.Chart.Name }}
