---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    {{ toYaml $.Values.nfc_monitoring.prometheus_adaptor.labels | nindent 4 }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/version: {{ $.Chart.Version }}
  name: prometheus-adapter
  namespace: monitoring
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{ toYaml $.Values.nfc_monitoring.prometheus_adaptor.labels | nindent 6 }}
      app.kubernetes.io/part-of: {{ $.Chart.Name }}
