---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
    app.kubernetes.io/version: {{ $.Chart.Version }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    prometheus: k8s
    role: grafana-agent-promtail
  name: grafana-agent
  namespace: monitoring
spec:
  groups:
  - name: grafana_agent
    rules:
    # - annotations:
    #     description: "As Grafana Agent is being used, it's version is set as promtails"
    - expr: |
        agent_build_info
      record: promtail_build_info
