---
apiVersion: rbac.authorization.k8s.io/v1
items:
{{ range .Values.nfc_monitoring.prometheus.monitor_namespaces }}
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    labels:
      {{ toYaml $.Values.nfc_monitoring.prometheus.labels | nindent 6 }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/part-of: {{ $.Chart.Name }}
      app.kubernetes.io/managed-by: {{ $.Release.Service }}
      app.kubernetes.io/version: {{ $.Chart.Version }}
    name: prometheus-{{ $.Release.Name }}
    namespace: {{ . | quote }}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: prometheus-{{ $.Release.Name }}
  subjects:
  - kind: ServiceAccount
    name: prometheus-{{ $.Release.Name }}
    namespace: {{ $.Values.nfc_monitoring.prometheus.namespace }}
{{ end }}

kind: RoleBindingList
