{{ if .Values.nfc_monitoring.thanos.sidecar.enabled }}
{{ if .Values.nfc_monitoring.thanos.sidecar.config }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{ toYaml $.Values.nfc_monitoring.prometheus.labels | nindent 4 }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/version: {{ $.Chart.Version }}
  name: thanos-sidecar-config
  namespace: monitoring
type: Opaque
stringData:
  thanos.yaml: |-
    {{ toYaml .Values.nfc_monitoring.thanos.sidecar.config | nindent 4 }}

{{ end }}
{{ end }}
