{{ if .Values.nfc_monitoring.thanos.sidecar.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: thanos-sidecar-config
  namespace: monitoring
type: Opaque
stringData:
  thanos.yaml: |-
    {{ toYaml .Values.nfc_monitoring.thanos.sidecar.config | nindent 4 }}

{{ end }}
