{{ if .Values.nfc_monitoring.kube_monitor_proxy.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: kube-monitor-proxy
  namespace: monitoring
  labels:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: kube-monitor-proxy
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
    app.kubernetes.io/version: {{ $.Chart.Version }}
    name_kcm: kube-controller-manager
    name_ks: kube-scheduler
spec:
  selector:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: kube-monitor-proxy
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
    
  ports:
    - name: kube-ctrl-mgr
      port: 10257
      targetPort: kube-ctrl-mgr
    - name: kube-scheduler
      port: 10259
      targetPort: kube-scheduler
  sessionAffinity: ClientIP

{{ end }}
