---
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  name: grafana-agent
  namespace: monitoring
  labels:
    {{ toYaml $.Values.nfc_monitoring.grafana_agent.labels | nindent 4 }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
    app.kubernetes.io/version: {{ $.Chart.Version }}
