---
apiVersion: v1
kind: Service
metadata:
  name: grafana-agent
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
    app.kubernetes.io/version: {{ $.Chart.Version }}
spec:
  selector:
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
  ports:
    - name: grafana-metrics
      port: 12345
      targetPort: grafana-metrics
    - name: kube-ctrl-mgr
      port: 11257
      targetPort: kube-ctrl-mgr
  #type: LoadBalancer
  sessionAffinity: ClientIP
