{{ if .Values.nfc_monitoring.grafana.enabled -}}
---
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  name: grafana
  namespace: {{ .Values.nfc_monitoring.grafana.namespace }}
  labels:
    {{ toYaml $.Values.nfc_monitoring.grafana.labels | nindent 4 }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
    app.kubernetes.io/version: {{ $.Chart.Version }}

{{- end }}
