---
{{- if .Values.nfc_monitoring.loki.enabled | default false -}}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: logging
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
    app.kubernetes.io/version: {{ $.Chart.Version }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}

  name: loki
  namespace: {{ .Values.nfc_monitoring.loki.namespace }}
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 15s
    port: loki
    # relabelings:
    # - action: replace
    #   regex: (.*)
    #   replacement: $1
    #   sourceLabels:
    #   - __meta_kubernetes_pod_node_name
    #   targetLabel: instance
    scheme: http
    # tlsConfig:
    #   insecureSkipVerify: true
  targetLabels:
    - cluster
  jobLabel: app.kubernetes.io/name
  selector:
{{ .Values.nfc_monitoring.loki.ServiceMonitor.selector | toYaml | indent 4 }}

{{- end -}}
