---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{ toYaml $.Values.nfc_monitoring.alert_manager.labels | nindent 4 }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/version: {{ $.Chart.Version }}
  name: alertmanager-main
  namespace: {{ .Values.nfc_monitoring.alert_manager.namespace | quote }}
spec:
  ports:
  - name: web
    port: 9093
    targetPort: web
  - name: reloader-web
    port: 8080
    targetPort: reloader-web
  selector:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
  sessionAffinity: ClientIP
