---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{ toYaml $.Values.nfc_monitoring.prometheus.labels | nindent 4 }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/version: {{ $.Chart.Version }}
  name: prometheus-k8s
  namespace: {{ .Values.nfc_monitoring.prometheus.namespace }}
spec:
  ports:
  - name: web
    port: 9090
    targetPort: web
  - name: reloader-web
    port: 8080
    targetPort: reloader-web
  selector:
    {{ toYaml $.Values.nfc_monitoring.prometheus.labels | nindent 4 }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
  sessionAffinity: ClientIP

{{ if .Values.nfc_monitoring.thanos.sidecar.enabled }}
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: prometheus-sidecar
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: thanos-sidecar
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/version: {{ $.Chart.Version }}
  name: thanos-sidecar
  namespace: {{ .Values.nfc_monitoring.prometheus.namespace }}
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 10901
    targetPort: 10901
  - name: http
    port: 10902
    targetPort: 10902
  selector:
    {{ toYaml $.Values.nfc_monitoring.prometheus.labels | nindent 4 }}

{{ end }}
