{{ if .Values.nfc_monitoring.grafana.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{ .Values.nfc_monitoring.grafana.namespace }}
  labels:
    {{ toYaml $.Values.nfc_monitoring.grafana.labels | nindent 4 }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
    app.kubernetes.io/version: {{ $.Chart.Version }}
spec:
  selector:
    {{ toYaml $.Values.nfc_monitoring.grafana.labels | nindent 4 }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
  #type: NodePort
  #type: LoadBalancer
  #clusterIP: None
  ports:
    - name: grafana
      port: 3000
      targetPort: grafana-http
      #nodePort: 3000
  #type: LoadBalancer
  sessionAffinity: ClientIP

{{- end }}
