{
 "title": "Cluster Overview",
 "tags": [
  "No Fuss Computing",
  "Overview",
  "Kubernetes"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Cluster Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Cores Available",
   "type": "stat",
   "description": "Total cluster CPU Cores not being utilised",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"idle\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total cluster CPU Cores",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(machine_cpu_cores)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Available",
   "type": "timeseries",
   "description": "Total memory for complete cluster",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable_bytes{node!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores Available",
   "type": "timeseries",
   "description": "Total cluster CPU Cores not being utilised",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"idle\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "stat",
   "description": "Total memory for complete cluster",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable_bytes{node!=\"\"})",
     "legendFormat": "Available w/o cached"
    },
    {
     "expr": "sum(node_memory_Cached_bytes{node!=\"\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Memory Size",
   "type": "stat",
   "description": "Total memory for complete cluster",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{node!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Ceph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Ceph health status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ceph_health_status{}", "legendFormat": "__auto" }
   ]
  },
  { "title": "Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Incoming log messages",
   "type": "stat",
   "description": "How many logs per minute are being received.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(loki_log_messages_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Daily log messages",
   "type": "stat",
   "description": "How many logs received in last 24 hours.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(loki_log_messages_total[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Messages Stored",
   "type": "stat",
   "description": "How many logs per minute are being received.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(loki_log_messages_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Incoming Metric Samples P/M",
   "type": "stat",
   "description": "How many metrics per minute are being received.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_head_samples_appended_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Daily Metric Samples",
   "type": "stat",
   "description": "How many metrics in the last 24 hours",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_head_samples_appended_total[5y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metric Samples Stored",
   "type": "stat",
   "description": "How many metrics are stored in the database",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_tsdb_head_samples_appended_total[5y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming",
   "type": "timeseries",
   "description": "How many logs per minute are being received.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(delta(loki_log_messages_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming Metric Samples P/M",
   "type": "timeseries",
   "description": "How many logs per minute are being received.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_head_samples_appended_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}